/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ufarm;

/**
 *
 * @author Jasmine
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        Upper = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        Produce = new javax.swing.JLabel();
        Farm = new javax.swing.JLabel();
        Feedback = new javax.swing.JLabel();
        Login = new javax.swing.JButton();
        Signup = new javax.swing.JButton();
        Upper2 = new javax.swing.JPanel();
        Welcome = new javax.swing.JLabel();
        Slogan = new javax.swing.JLabel();
        OrderProduce = new javax.swing.JButton();
        Featured = new javax.swing.JLabel();
        Fea1 = new javax.swing.JPanel();
        Fea2 = new javax.swing.JPanel();
        Fea3 = new javax.swing.JPanel();
        Seasonal = new javax.swing.JLabel();
        Sea1 = new javax.swing.JPanel();
        Sea2 = new javax.swing.JPanel();
        Sea3 = new javax.swing.JPanel();
        Sea4 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BG.setToolTipText("");

        Upper.setBackground(new java.awt.Color(0, 0, 0));
        Upper.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                UpperComponentResized(evt);
            }
        });

        Title.setFont(new java.awt.Font("Georgia", 1, 20)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("UFARM");

        Home.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        Home.setForeground(new java.awt.Color(255, 255, 255));
        Home.setText("HOME");

        Produce.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        Produce.setForeground(new java.awt.Color(255, 255, 255));
        Produce.setText("PRODUCE");

        Farm.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        Farm.setForeground(new java.awt.Color(255, 255, 255));
        Farm.setText("FARM");

        Feedback.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        Feedback.setForeground(new java.awt.Color(255, 255, 255));
        Feedback.setText("FEEDBACK");

        Login.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        Login.setText("LOGIN");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });

        Signup.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        Signup.setText("SIGNUP");
        Signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UpperLayout = new javax.swing.GroupLayout(Upper);
        Upper.setLayout(UpperLayout);
        UpperLayout.setHorizontalGroup(
            UpperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpperLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Home)
                .addGap(31, 31, 31)
                .addComponent(Produce)
                .addGap(43, 43, 43)
                .addComponent(Farm)
                .addGap(43, 43, 43)
                .addComponent(Feedback)
                .addGap(46, 46, 46)
                .addComponent(Login)
                .addGap(32, 32, 32)
                .addComponent(Signup)
                .addGap(47, 47, 47))
        );
        UpperLayout.setVerticalGroup(
            UpperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpperLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UpperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Login)
                    .addComponent(Signup)
                    .addComponent(Farm)
                    .addComponent(Produce)
                    .addComponent(Home)
                    .addComponent(Title)
                    .addComponent(Feedback))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Upper2.setBackground(new java.awt.Color(204, 204, 204));

        Welcome.setFont(new java.awt.Font("Georgia", 1, 33)); // NOI18N
        Welcome.setForeground(new java.awt.Color(35, 101, 51));
        Welcome.setText("WELCOME TO UFARM!");

        Slogan.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Slogan.setText("Connecting urban farmers and local consumers.");

        OrderProduce.setBackground(new java.awt.Color(35, 101, 51));
        OrderProduce.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        OrderProduce.setForeground(new java.awt.Color(255, 255, 255));
        OrderProduce.setText("Order Produce");
        OrderProduce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderProduceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Upper2Layout = new javax.swing.GroupLayout(Upper2);
        Upper2.setLayout(Upper2Layout);
        Upper2Layout.setHorizontalGroup(
            Upper2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Upper2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Upper2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Upper2Layout.createSequentialGroup()
                        .addGroup(Upper2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Slogan)
                            .addComponent(Welcome))
                        .addGap(177, 177, 177))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Upper2Layout.createSequentialGroup()
                        .addComponent(OrderProduce)
                        .addGap(294, 294, 294))))
        );
        Upper2Layout.setVerticalGroup(
            Upper2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Upper2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(Welcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Slogan)
                .addGap(18, 18, 18)
                .addComponent(OrderProduce, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        Featured.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        Featured.setText("FEATURED FARMS");

        Fea1.setBackground(new java.awt.Color(35, 101, 51));

        javax.swing.GroupLayout Fea1Layout = new javax.swing.GroupLayout(Fea1);
        Fea1.setLayout(Fea1Layout);
        Fea1Layout.setHorizontalGroup(
            Fea1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 181, Short.MAX_VALUE)
        );
        Fea1Layout.setVerticalGroup(
            Fea1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        Fea2.setBackground(new java.awt.Color(35, 101, 51));

        javax.swing.GroupLayout Fea2Layout = new javax.swing.GroupLayout(Fea2);
        Fea2.setLayout(Fea2Layout);
        Fea2Layout.setHorizontalGroup(
            Fea2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 181, Short.MAX_VALUE)
        );
        Fea2Layout.setVerticalGroup(
            Fea2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        Fea3.setBackground(new java.awt.Color(35, 101, 51));

        javax.swing.GroupLayout Fea3Layout = new javax.swing.GroupLayout(Fea3);
        Fea3.setLayout(Fea3Layout);
        Fea3Layout.setHorizontalGroup(
            Fea3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 181, Short.MAX_VALUE)
        );
        Fea3Layout.setVerticalGroup(
            Fea3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        Seasonal.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        Seasonal.setText("SEASONAL PRODUCE");

        Sea1.setBackground(new java.awt.Color(35, 101, 51));

        javax.swing.GroupLayout Sea1Layout = new javax.swing.GroupLayout(Sea1);
        Sea1.setLayout(Sea1Layout);
        Sea1Layout.setHorizontalGroup(
            Sea1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
        );
        Sea1Layout.setVerticalGroup(
            Sea1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 142, Short.MAX_VALUE)
        );

        Sea2.setBackground(new java.awt.Color(35, 101, 51));

        javax.swing.GroupLayout Sea2Layout = new javax.swing.GroupLayout(Sea2);
        Sea2.setLayout(Sea2Layout);
        Sea2Layout.setHorizontalGroup(
            Sea2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
        );
        Sea2Layout.setVerticalGroup(
            Sea2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 142, Short.MAX_VALUE)
        );

        Sea3.setBackground(new java.awt.Color(35, 101, 51));

        javax.swing.GroupLayout Sea3Layout = new javax.swing.GroupLayout(Sea3);
        Sea3.setLayout(Sea3Layout);
        Sea3Layout.setHorizontalGroup(
            Sea3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
        );
        Sea3Layout.setVerticalGroup(
            Sea3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 142, Short.MAX_VALUE)
        );

        Sea4.setBackground(new java.awt.Color(35, 101, 51));

        javax.swing.GroupLayout Sea4Layout = new javax.swing.GroupLayout(Sea4);
        Sea4.setLayout(Sea4Layout);
        Sea4Layout.setHorizontalGroup(
            Sea4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
        );
        Sea4Layout.setVerticalGroup(
            Sea4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 142, Short.MAX_VALUE)
        );

        jSeparator2.setForeground(new java.awt.Color(35, 101, 51));

        javax.swing.GroupLayout BGLayout = new javax.swing.GroupLayout(BG);
        BG.setLayout(BGLayout);
        BGLayout.setHorizontalGroup(
            BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Upper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Upper2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BGLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BGLayout.createSequentialGroup()
                        .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Fea2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Featured))
                        .addGap(104, 104, 104)
                        .addComponent(Fea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Fea3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))
                    .addGroup(BGLayout.createSequentialGroup()
                        .addComponent(Seasonal)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(BGLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BGLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(Sea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(Sea2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(Sea3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(Sea4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        BGLayout.setVerticalGroup(
            BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BGLayout.createSequentialGroup()
                .addComponent(Upper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Upper2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Featured)
                .addGap(31, 31, 31)
                .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Fea2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fea3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Seasonal)
                .addGap(39, 39, 39)
                .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Sea2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sea3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sea4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpperComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_UpperComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_UpperComponentResized

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginActionPerformed

    private void SignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignupActionPerformed

    private void OrderProduceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderProduceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OrderProduceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JPanel BG1;
    private javax.swing.JLabel Farm;
    private javax.swing.JLabel Farm1;
    private javax.swing.JPanel Fea1;
    private javax.swing.JPanel Fea2;
    private javax.swing.JPanel Fea3;
    private javax.swing.JPanel Fea6;
    private javax.swing.JLabel Featured;
    private javax.swing.JLabel Feedback;
    private javax.swing.JLabel Feedback1;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel Home1;
    private javax.swing.JButton Login;
    private javax.swing.JButton Login1;
    private javax.swing.JButton OrderProduce;
    private javax.swing.JLabel Produce;
    private javax.swing.JLabel Produce1;
    private javax.swing.JPanel Sea1;
    private javax.swing.JPanel Sea2;
    private javax.swing.JPanel Sea3;
    private javax.swing.JPanel Sea4;
    private javax.swing.JLabel Seasonal;
    private javax.swing.JButton Signup;
    private javax.swing.JButton Signup1;
    private javax.swing.JLabel Slogan;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel Title1;
    private javax.swing.JPanel Upper;
    private javax.swing.JPanel Upper1;
    private javax.swing.JPanel Upper2;
    private javax.swing.JLabel Welcome;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
